"""Page 5: Quick Transform — upload pre-computed files, align + merge, download."""

import subprocess
import tempfile
import zipfile
import sys
from pathlib import Path

import streamlit as st

SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from align_audio import align_segments
from merge_video import merge_audio_video

st.header("Quick Transform")
st.caption(
    "Upload a video with its Colab-generated translation and TTS segments "
    "to produce the final English-dubbed video."
)

# ── Session state ─────────────────────────────────────────────────────────────

if "transform_result" not in st.session_state:
    st.session_state.transform_result = None

if "transform_last_file_id" not in st.session_state:
    st.session_state.transform_last_file_id = None

# ── File uploads ──────────────────────────────────────────────────────────────

col_left, col_right = st.columns(2)

with col_left:
    uploaded_video = st.file_uploader(
        "Video file",
        type=["mp4", "mkv", "avi", "mov"],
        key="transform_video",
    )

with col_right:
    uploaded_translation = st.file_uploader(
        "Translation JSON (*_en.json)",
        type=["json"],
        key="transform_translation",
        help="The translated JSON from the pipeline (contains timestamps + English text).",
    )

uploaded_tts = st.file_uploader(
    "TTS segments (ZIP of WAV files)",
    type=["zip"],
    key="transform_tts",
    help="ZIP archive of the per-segment WAV files generated by F5-TTS in Colab.",
)

# Reset result when a new video is uploaded
if uploaded_video and uploaded_video.file_id != st.session_state.transform_last_file_id:
    st.session_state.transform_result = None
    st.session_state.transform_last_file_id = uploaded_video.file_id

if uploaded_video:
    with st.expander("Preview uploaded video"):
        st.video(uploaded_video)

# ── Guards ────────────────────────────────────────────────────────────────────

missing = []
if not uploaded_video:
    missing.append("video")
if not uploaded_translation:
    missing.append("translation JSON")
if not uploaded_tts:
    missing.append("TTS segments ZIP")

if missing:
    st.info(f"Upload the following to continue: {', '.join(missing)}")

# ── Transform ─────────────────────────────────────────────────────────────────

can_run = uploaded_video and uploaded_translation and uploaded_tts

if can_run:
    if st.button("Transform Video", type="primary", use_container_width=True):

        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp = Path(tmp_dir)

            # Write uploaded files to disk
            video_path = tmp / uploaded_video.name
            video_path.write_bytes(uploaded_video.getvalue())

            translation_path = tmp / "translation_en.json"
            translation_path.write_bytes(uploaded_translation.getvalue())

            tts_dir = tmp / "tts_segments"
            tts_dir.mkdir()
            with zipfile.ZipFile(uploaded_tts) as zf:
                zf.extractall(tts_dir)

            # Flatten: if ZIP contained a subfolder, move WAVs up to tts_dir
            wav_files = list(tts_dir.rglob("*.wav"))
            for wav in wav_files:
                if wav.parent != tts_dir:
                    wav.rename(tts_dir / wav.name)

            result_bytes = None

            with st.status("Processing...", expanded=True) as status:
                try:
                    # Step 1 — Align TTS segments to original timing
                    st.write("Aligning TTS segments to video timing...")
                    aligned_path = tmp / "aligned_en.wav"
                    align_segments(translation_path, tts_dir, aligned_path)

                    # Step 2 — Merge aligned audio into video
                    st.write("Merging audio + video...")
                    out_path = tmp / f"{video_path.stem}_EN.mp4"
                    merge_audio_video(video_path, aligned_path, out_path)

                    result_bytes = out_path.read_bytes()
                    status.update(label="Done!", state="complete")

                except subprocess.CalledProcessError as e:
                    status.update(label="FFmpeg error", state="error")
                    st.error(f"FFmpeg error:\n{e.stderr.decode()}")
                except Exception as e:
                    status.update(label=f"Error: {e}", state="error")
                    st.exception(e)

            if result_bytes:
                st.session_state.transform_result = {
                    "bytes": result_bytes,
                    "filename": f"{Path(uploaded_video.name).stem}_EN.mp4",
                }

# ── Download ──────────────────────────────────────────────────────────────────

if st.session_state.transform_result:
    st.success("Your English video is ready!")
    st.download_button(
        label="Download English video",
        data=st.session_state.transform_result["bytes"],
        file_name=st.session_state.transform_result["filename"],
        mime="video/mp4",
        use_container_width=True,
        type="primary",
    )
